apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: default
type: Opaque
stringData:                        # stringData auto base64-encodes for you
  jwt-secret: *********
  jwt-refresh-secret: **********
  # Full connection string — used by microservices
  mongo-uri: 'mongodb://<USERNAME>:<PASSWORD>@mongodb-service:27017/auth_service?authSource=admin'
